package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"

	"github.com/clawscli/claws/internal/genimports"
)

const outputFileName = "cmd/claws/imports_custom.go"

func main() {
	projectRoot, err := genimports.GetProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting project root: %v\n", err)
		os.Exit(1)
	}

	packages, err := genimports.FindRegisterPackages(projectRoot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding register packages: %v\n", err)
		os.Exit(1)
	}

	grouped := genimports.GroupByService(packages)

	content := generateImportsFile(grouped)

	formatted, err := format.Source(content)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting generated code: %v\n", err)
		fmt.Fprintf(os.Stderr, "Raw content:\n%s\n", content)
		os.Exit(1)
	}

	outputFile := filepath.Join(projectRoot, outputFileName)
	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d imports\n", outputFileName, len(packages))
}

func generateImportsFile(grouped map[string][]string) []byte {
	var buf bytes.Buffer

	buf.WriteString(`// Code generated by go generate; DO NOT EDIT.
// To regenerate: task gen-imports
//
// This file contains blank imports that register custom resource implementations.
// Each import triggers the init() function in that package, which registers
// the DAO and Renderer with the global registry.

package main

import (
`)

	var services []string
	for service := range grouped {
		services = append(services, service)
	}
	sort.Strings(services)

	for i, service := range services {
		if i > 0 {
			buf.WriteString("\n")
		}

		displayName := genimports.GetServiceDisplayName(service)
		fmt.Fprintf(&buf, "\t// %s\n", displayName)

		packages := grouped[service]
		sort.Strings(packages)
		for _, pkg := range packages {
			fmt.Fprintf(&buf, "\t_ %q\n", pkg)
		}
	}

	buf.WriteString(")\n")

	return buf.Bytes()
}
